name: Feature request 💄
description: Suggest a new idea or an improvement for Vitamin Design.
labels: ['enhancement 🚀']
body:
  - type: markdown
    attributes:
      value: |
        Please provide the clearest summary of your purpose. This will help us to answer you quickly and accurately.
        Thanks for contributing by creating this issue! ❤️
  - type: checkboxes
    attributes:
      label: Duplicates ❌
      description: Please [search the history](https://github.com/Decathlon/vitamin-design/issues) to see if an issue already exists for the same problem.
      options:
        - label: I have searched the existing issues
          required: true
  - type: checkboxes
    id: library
    attributes:
      label: Libraries
      description: Which Figma library/libraries is/are concerned?
      options:
        - label: Vitamin Web UI Kit
        - label: Vitamin Android UI Kit
        - label: Vitamin iOS UI Kit
        - label: Vitamin Icons
        - label: Vitamin Assets
        - label: Vitamin Core theme (Light mode)
        - label: Vitamin Core theme (Dark mode)
        - label: Vitamin Base colors palette
        - label: Vitamin Extras kit
        - label: Not related to one Figma library
    validations:
      required: true
  - type: textarea
    attributes:
      label: Summary 💡
      description: Describe how it should work.
  - type: textarea
    attributes:
      label: Dependencies 📦
      description: Link issues it depends of.
  - type: textarea
    attributes:
      label: Examples 🌈
      description: Provide a link to the specification, other implementations, or screenshots of the expected behavior.
  - type: textarea
    attributes:
      label: Motivation 🔦
      description: What are you trying to accomplish? How has the lack of this feature affected you? Providing context helps us come up with a solution that is more useful in the real world.
  - type: markdown
    attributes:
      value: |
        # Checklists ✔
        
        In order to track and ensure we don't forget anything when we change from one column to another in our [Design workflow](https://github.com/orgs/Decathlon/projects/3), we use checklists. 
        
        _Please, let these checklists unchecked when you create the issue and keep them up-to-date when you work on it. Thanks a lot! ❤️_
  - type: checkboxes
    attributes:
      label: New 🆕
      options:
        - label: Validated in a grooming session
  - type: checkboxes
    attributes:
      label: Backlog 📋 
      options:
        - label: Has a good summary
        - label: Has example link(s)
  - type: checkboxes
    attributes:
      label: Design in progress 🏗 
      options:
        - label: Analysis _(functional & technical)_
        - label: Design refinement
        - label: Dev qualification _(properties, breakpoints, tokens etc.)_
        - label: Documentation refinement _(inside the Figma branch)_
  - type: checkboxes
    attributes:
      label: Design review 👀
      options:
        - label: Figma branch merged
        - label: Documentation review _(and move the documentation into Vitamin Documentation Figma file)
      
