name: Icon request 🖍
description: Suggest a new icon for Vitamin Design.
labels: ['enhancement 🚀', 'android 🟢', 'ios 🟡', 'web 🔵', 'icons ✨']
body:
  - type: markdown
    attributes:
      value: |
        Please provide the clearest summary of your purpose. This will help us to answer you quickly and accurately.
        Thanks for contributing by creating this issue! ❤️
  - type: checkboxes
    attributes:
      label: Duplicates ❌
      description: Before submitting artwork or a request, first review our [icon library](https://www.figma.com/community/file/1116657129289164847) and [search the history](https://github.com/Decathlon/vitamin-design/issues) to see if an issue already exists for the same icon.
      options:
        - label: I have searched the existing icons and issues
          required: true
  - type: textarea
    attributes:
      label: Summary 💡
      description: Describe the meaning, the contexte and the usage of your icon.
  - type: textarea
    attributes:
      label: Examples 🌈
      description: Provide a link to the specification, other implementations, or screenshots of the expected behavior.
  - type: markdown
    attributes:
      value: |
        # Checklists ✔
        
        In order to track and ensure we don't forget anything when we change from one column to another in our [Design workflow](https://github.com/orgs/Decathlon/projects/3), we use checklists. 
        
        _Please, let these checklists unchecked when you create the issue and keep them up-to-date when you work on it. Thanks a lot! ❤️_
  - type: checkboxes
    attributes:
      label: New 🆕
      options:
        - label: Validated in a grooming session
  - type: checkboxes
    attributes:
      label: Backlog 📋 
      options:
        - label: Has a good summary
        - label: Has example link(s)
  - type: checkboxes
    attributes:
      label: Design in progress 🏗 
      options:
        - label: Analysis _(functional & technical)_
        - label: Design refinement
  - type: checkboxes
    attributes:
      label: Design review 👀
      options:
        - label: Figma branch merged
  - type: checkboxes
    attributes:
      label: Ready to dev 👍
      options:
        - label: Issues are created in all repositories affected _(vitamin-<web,android,ios,compose>)_
  - type: checkboxes
    attributes:
      label: Dev in progress 💻
      options:
        - label: All issues are resolved _(to replace with issues links)_
      
