name: Propose new icon ✨
description: For new icon contributions and suggestions for vitamin-icons.
title: '[Icon]: New icon <icon-name>'
labels: ['enhancement 🚀', 'android 🟢', 'ios 🟡', 'web 🔵', 'icons ✨', 'run 💨']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out the proposal for a new icon!
        - type: markdown
  - type: checkboxes
    attributes:
      label: Duplicates ❌
      description: Before submitting artwork or a request, first review our [icon library](https://www.figma.com/community/file/1116657129289164847) and [search the history](https://github.com/Decathlon/vitamin-design/issues) to see if an issue already exists for the same icon.
      options:
        - label: I have searched the existing icons and requests.
          required: true
  - type: input
    id: icon-name
    attributes:
      label: Icon name
    validations:
      required: true
  - type: textarea
    id: icon-description
    attributes:
      label: Icon description
      description: |
        **How will these icons be used?**
        **Action:** Used to denote _x action_.
        **Wayfinding:** Used to help users to _x_.
        **Concept:** Used to represent _x_.
        **Education:** Used to give users more information about _context x_.
        Relevant screenshots or links to design files detailing the user experience, the reason for creating the new icon, and any additional context.
    validations:
      required: true
      render: shell
  - type: input
    id: icon-keywords
    attributes:
      label: Icon keywords
      description: Comma-delimited string of keywords, e.g. member, sport, health
  - type: input
    id: icon-author
    attributes:
      label: Icon author
      description: Comma-delimited string of authors first and last name, e.g. Gaël Monfils, Teddy Riner
  - type: textarea
    id: icon-svg
    attributes:
      label: Icon SVG code
      value: <svg>...</svg>
      render: shell
  - type: textarea
    id: icon-other-details
    attributes:
      label: Are there any other important details?
      
