name: Propose a new icon or asset ✨🏞
description: For new icon & asset contributions and suggestions for vitamin-icons or vitamin-assets.
title: 'Add a new <icon-or-asset-name>'
labels: ['enhancement 🚀', 'android 🟢', 'ios 🟡', 'web 🔵', 'run 💨']
body:
  - type: markdown
    attributes:
      value: |
        Please provide the clearest summary of your purpose. This will help us to answer you quickly and accurately.
        Thanks for contributing by creating this issue! ❤️
  - type: checkboxes
    attributes:
      label: Duplicates ❌
      description: Before submitting artwork or a request, first review our [icons library](https://www.figma.com/community/file/1116657129289164847 or [assets library](https://www.figma.com/community/file/1116658372075701302) and [search the history](https://github.com/Decathlon/vitamin-design/issues) to see if an issue already exists for the same icon.
      options:
        - label: I have searched the existing icons or assets and requests.
          required: true
  - type: dropdown
    id: library
    attributes:
      label: Which Figma library is concerned?
      options:
        - Vitamin Icons
        - Vitamin Assets
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Remix icon check (only for icons)
      description: Our icons come from an open source library called [Remix icon](https://remixicon.com/) which contain more than 2000 icons, the icon you're looking for is probably already available on Remix.
      options:
        - label: I have searched if the icon is already available on Remix.
          required: false
  - type: input
    id: icon-asset-name
    attributes:
      label: Icon or Asset name
    validations:
      required: true
  - type: textarea
    id: icon-asset-description
    attributes:
      label: Icon or Asset description
      description: |
        **How will these icons or assets be used?**
        **Action:** Used to denote _x action_.
        **Wayfinding:** Used to help users to _x_.
        **Concept:** Used to represent _x_.
        **Education:** Used to give users more information about _context x_.
        Relevant screenshots or links to design files detailing the user experience, the reason for creating the new icon, and any additional context.
    validations:
      required: true
      render: shell
  - type: input
    id: icon-asset-keywords
    attributes:
      label: Icon or Assets keywords
      description: Comma-delimited string of keywords, e.g. member, sport, health
  - type: input
    id: icon-asset-author
    attributes:
      label: Icon or Asset author
      description: Comma-delimited string of authors first and last name, e.g. Gaël Monfils, Teddy Riner
  - type: textarea
    id: icon-asset-svg
    attributes:
      label: Icon or Asset SVG code
      value: <svg>...</svg>
      render: shell
  - type: textarea
    id: icon-asset-other-details
    attributes:
      label: Are there any other important details?
      
