name: Propose a new asset ✨
description: For new asset contributions and suggestions for vitamin-assets.
title: 'Add a new asset <asset-name>'
labels: ['enhancement 🚀', 'android 🟢', 'ios 🟡', 'web 🔵', 'assets 🏞', 'run 💨']
body:
  - type: markdown
    attributes:
      value: |
        Please provide the clearest summary of your purpose. This will help us to answer you quickly and accurately.
        Thanks for contributing by creating this issue! ❤️
  - type: checkboxes
    attributes:
      label: Duplicates ❌
      description: Before submitting artwork or a request, first review our [assets library](https://www.figma.com/community/file/1116658372075701302) and [search the history](https://github.com/Decathlon/vitamin-design/issues) to see if an issue already exists for the same asset.
      options:
        - label: I have searched the existing assets and requests.
          required: true
  - type: input
    id: asset-name
    attributes:
      label: Asset name
    validations:
      required: true
  - type: textarea
    id: asset-description
    attributes:
      label: Asset description
      description: |
        **How will these assets be used?**
        **Action:** Used to denote _x action_.
        **Wayfinding:** Used to help users to _x_.
        **Concept:** Used to represent _x_.
        **Education:** Used to give users more information about _context x_.
        Relevant screenshots or links to design files detailing the user experience, the reason for creating the new asset, and any additional context.
    validations:
      required: true
      render: shell
  - type: input
    id: asset-keywords
    attributes:
      label: Asset keywords
      description: Comma-delimited string of keywords, e.g. member, sport, health
  - type: input
    id: asset-author
    attributes:
      label: Asset author
      description: Comma-delimited string of authors first and last name, e.g. Gaël Monfils, Teddy Riner
  - type: textarea
    id: asset-svg
    attributes:
      label: Asset SVG code
      value: <svg>...</svg>
      render: shell
  - type: textarea
    id: asset-other-details
    attributes:
      label: Are there any other important details?
      
