name: '[Auto] PR icons'

on:
  push:
    branches: [main]
    paths:
      - 'build/icons/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
