name: '[Auto] PR assets'

on:
  push:
    branches: [main]
    paths:
      - 'build/assets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create Pull Request for assets on vitamin-web
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_folder: 'build/assets/svg'
          destination_repo: 'Decathlon/vitamin-web'
          destination_folder: 'packages/sources/assets/src/generated/assets'
          destination_base_branch: 'main'
          destination_head_branch: 'feat/update-assets'
          user_email: 'laurent.thiebault@decathlon.com'
          user_name: 'lauthieb'

      - name: Create Pull Request for assets on vitamin-android
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_folder: 'build/assets/drawable'
          destination_repo: 'Decathlon/vitamin-android'
          destination_folder: 'foundation/foundation-assets/src/main/res'
          destination_base_branch: 'main'
          destination_head_branch: 'feat/update-assets'
          user_email: 'laurent.thiebault@decathlon.com'
          user_name: 'lauthieb'

      - name: Create Pull Request for icons on vitamin-compose
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_folder: 'build/assets/compose'
          destination_repo: 'Decathlon/vitamin-compose'
          destination_folder: 'foundation/foundation-assets/src/main/kotlin/com/decathlon/vitamin'
          destination_base_branch: 'main'
          destination_head_branch: 'feat/update-assets'
          user_email: 'laurent.thiebault@decathlon.com'
          user_name: 'lauthieb'
