name: '[Manual] [vitamin-android] Manual PR assets'

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create Pull Request for assets on vitamin-android
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_folder: 'build/assets/drawable'
          destination_repo: 'Decathlon/vitamin-android'
          destination_folder: 'foundation/foundation-assets/src/main/res'
          destination_base_branch: 'main'
          destination_head_branch: 'feat/update-assets'
          user_email: 'laurent.thiebault@decathlon.com'
          user_name: 'lauthieb'
